### ISSUE TITLE
some ASCII and CheckIp

### ISSUE THREAD

**Issue by lillstrumpa** [GouveaHeitor/nipe#100]
I like the script it works like a charm, but Im always running the perl nipe.pl status script like every 10min , I guess tor jumps ip after 10min.

I dont know how to code, and this is my first attempt to mod something, 
It would be nice to see a count down timer for the next status update,
my attempt to contribute with something, 

my nipe.pl file
******************
#!/usr/bin/perl

#########################################################
# Nipe developed by Heitor Gouvêa                       #
# This work is licensed under MIT License               #
# Copyright (c) 2015 - 2019 Heitor Gouvêa               #
#                                                       #
# [+] AUTOR:        Heitor Gouvêa                       #
# [+] EMAIL:        hi@heitorgouvea.me                  #
# [+] SITE:         https://heitorgouvea.me             #
# [+] GITHUB:       https://github.com/GouveaHeitor     #
# [+] TWITTER:      @GouveaHeitor                       #
#                                                       #
# [+] Moded by lillstrumpa                                    #
#########################################################

use Switch;
use lib "./lib/";
use Nipe::Stop;
use Nipe::Start;
use Nipe::CheckIp;
use Nipe::Functions;

sub main {
	my $command = $ARGV[0];

	switch ($command) {
		case "stop" {
			Nipe::Stop -> new();
		}

		case "start" {
			Nipe::Start -> new();
	while (1) {
		sleep(10);
			print"\033[2J\033[;H";
			print "\033[1;35m
                      -.                          
                     `.+/.                        
                     ./os+.`                      
                      `/ys-`                      
                      .oyo-`                      
                     `/ssss-                      
                  `-+ssssoooo/-`                  
                -/ooosooooooooss/.                
              -oso+osoooooooooooss+.              
             /sso+oso+o++n+o+oooosss:             
            /sso+oos+o+++i++o+soosssy:            
           `sss+ooss+++++p++++sooossyy`           
           -ysooooss++o+oe+o++oooosssy-           
           `yssoosssoooooooo++sooosssy.           
            +yssssosoooooooooosoosssy+            
             +yyyysysyy\033[1;37mNIPE\033[1;35msysysysssy+             
              -syyyyyyyyyyyysyyyyyo-              
               `-/oyhyhhhhyyhyso/.`               
              \033[1;37m......\033[1;35m-oyyyyso:\033[1;37m.......              
             ``........\033[1;35m-\033[1;37m.........``              
                   ````````````                   
                                                   ";
print "\r\033[1;37mMake \033[1;34m\TOR\033[1;37m your deafult Network Gateway";
		Nipe::CheckIp -> new();
		print "Ctrl+Z to exit\n";
	}
		}

		case "status" {
			Nipe::CheckIp -> new();
		}

		case "restart" {
			Nipe::Stop -> new();
			Nipe::Start -> new();
		}

		case "install" {
			Nipe::Functions -> install();
		}

		Nipe::Functions -> help();
	}
}

main();
exit;

**Comment by GouveaHeitor** [comment]
Hi @lillstrumpa,

I am happy to read your testimony about Nipe and I really appreciate your effort!
Unfortunately, I want to keep Nipe as a "simple and clean" tool. I feel a little uncomfortable when I run a tool and it generates some outputs that are not very useful, so I want to keep the nipe away from that.

Unfortunately I will close this issue, ok? But I still look forward to contributions coming from you in the future!

Thx

**Comment by lillstrumpa** [comment]
ok

**Comment by GouveaHeitor** [comment]
About IP exchange: the average average duration of a tor circuit is exactly 10 minutes. If you want to recreate the circuit before this time, to change your IP, just execute the "restart" command of the nipe.

**Comment by GouveaHeitor** [comment]
Thx!
