### ISSUE TITLE
Ip table invalid argument 

### ISSUE THREAD

**Issue by sam1466** [GouveaHeitor/nipe#101]
When I run the script it shows 
Iptbales v1.8.4 (nf_tables): Could not fetch rule set generation I'd: Invalid argument.
Pls help waiting for your reply

**Comment by GouveaHeitor** [comment]
Hi @sam1466,

You can try to test Nipe again? I think this is resolved with the lasted commit.

Thx

**Comment by GouveaHeitor** [comment]
Hi @sam1466,
Any updates?

**Comment by GouveaHeitor** [comment]
Hi @sam1466, if I don't have an answer in the next few days, I will close this issue as resolved...

**Comment by GouveaHeitor** [comment]
Any update?
