### ISSUE TITLE
perl nipe.pl install

### ISSUE THREAD

**Issue by aneeshraj1999** [GouveaHeitor/nipe#105]
error: only one operation may be used at a time

**Comment by GouveaHeitor** [comment]
Hi @aneeshraj1999,

Which command did you execute? That doesn't seem like a common mistake in Nipe...

**Comment by GouveaHeitor** [comment]
Any update?

**Comment by GouveaHeitor** [comment]
As you did not give me any feedback, I will close this issue, however, feel free to open it again.
Thx!
