### ISSUE TITLE
No consigo instalar el script nipe perl

### ISSUE THREAD

**Issue by Alexxm17** [GouveaHeitor/nipe#106]
Buenas, acabo de crear un sistema operativo debian 10 en una maquina virtual para hacer pruebas con el y poder torificarlo con el script perl nipe, pero al ejecutar el comando sudo cpan install Switch JSON Config :: Simple no me acaba diciendo siempre que No such file or directory. Por si puede ser un problema al ejecutar el comando estoy en /Escritorio/nipe Alguien sabe como arreglar esto porfavor?
Muchas Gracias

**Comment by GouveaHeitor** [comment]
Hi @Alexxm17, we can talk in English?
Can you send me all your error output please?

**Comment by GouveaHeitor** [comment]
Hi @Alexxm17, if I don't have an answer in the next few days, I will close this issue as resolved...

**Comment by GouveaHeitor** [comment]
Any update?

**Comment by GouveaHeitor** [comment]
As you did not give me any feedback, I will close this issue, however, feel free to open it again.
Thx!
