### ISSUE TITLE
[!] ERROR: sorry, it was not possible to establish a connection to the server.

### ISSUE THREAD

**Issue by omaithatsnice** [GouveaHeitor/nipe#12]
Hello, love the concept of this but cannot for the life of me to get it to work properly.

Attempting to get it to run on BlackArch (in VM). 

BlackArch repositories do include nipe, but I removed that and grabbed it from the git repositories as your installation instructions say to do. Followed all instructions, received no errors. When I attempt to run 'perl nipe.pl start' I receive the error.

iptables version 1.6.1
perl version 5.26.0

EDIT: After playing around with everything for a bit, noticed that tor.service keeps failing:
> * tor.service - Anonymizing Overlay Network
>   Loaded: loaded (/usr/lib/systemd/system/tor.service; enabled; vendor preset: disabled)
>   Active: failed (Result: exit-code) since Tue 2018-01-23 00:21:44 UTC; 5s ago
>  Process: 16543 ExecStart=/usr/bin/tor -f /etc/tor/torrc (code=exited, status=1/FAILURE)
> Main PID: 16543 (code=exited, status=1/FAILURE)
>
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.710 [warn] Error setting configured user: debian-tor not found
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.710 [warn] Before Tor can create a control socket in "/var/run/tor/control", the directory "/var/run/tor" needs to ex
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.711 [notice] Closing partially-constructed Socks listener on 127.0.0.1:9050
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.711 [notice] Closing partially-constructed DNS listener on 127.0.0.1:9061
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.711 [notice] Closing partially-constructed Transparent pf/netfilter listener on 127.0.0.1:9051
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.711 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
>Jan 23 00:21:44 blackarch tor[16543]: Jan 23 00:21:44.711 [err] Reading config failed--see warnings above.
>Jan 23 00:21:44 blackarch systemd[1]: tor.service: Main process exited, code=exited, status=1/FAILURE
>Jan 23 00:21:44 blackarch systemd[1]: tor.service: Unit entered failed state.
Jan 23 00:21:44 blackarch systemd[1]: tor.service: Failed with result 'exit-code'.

If I remove tor and reinstall from pacman repo, tor.service will load and connect just fine. It's after I run `perl nipe.pl install`
That tor.service fails to work. I think some setting the script puts into tor is causing it to fail?

**Comment by victorperin** [comment]
We could try using a docker container to help reproduce this bug.

This one seems a good one: https://hub.docker.com/r/heichblatt/blackarch/~/dockerfile/

When I get time I could help with it.

**Comment by gerardo-junior** [comment]
I tried installing on the arch, and I think this question is related to the return of the command "cat / etc / os-release | grep 'ID_LIKE' | cut -d '=' -f 2". The blackarch it is a nearly a meta-distro that can be installed upon archlinux or not, that return varies a little bit from the arch, archlinux, blackarch etc ... I do not think it's provided in getSystem(), which makes it impossible to get the torrc file.

Hope this helps

**Comment by GouveaHeitor** [comment]
Fixed this on #9998dd4bfa0e299e24a36afe50e653ba6d9efbb0 commit

**Comment by GouveaHeitor** [comment]
Fixed this bug on 9998dd4bfa0e299e24a36afe50e653ba6d9efbb0 commit
