### ISSUE TITLE
Criar um flatpak do nipe

### ISSUE THREAD

**Issue by LeandroStanger** [GouveaHeitor/nipe#13]

**Comment by GouveaHeitor** [comment]
Can you explain the reason for this issue better?!

**Comment by GouveaHeitor** [comment]
Melhorou!!! É uma ótima sugestão! Vou tentar providenciar isso o mais rápido possível!

**Comment by LeandroStanger** [comment]
Vai criar no [flathub](flathub.org)?

**Comment by GouveaHeitor** [comment]
Consegue me ajudar com isso @LeandroStanger?

**Comment by LeandroStanger** [comment]
Manda um E-Mail para o Flathub que eles te ajudam
 admins@flathub.org
