### ISSUE TITLE
Contribute guidelines

### ISSUE THREAD

**Issue by victorperin** [GouveaHeitor/nipe#14]
We should build some guidelines to help people contribute in a faster way to the repo.

I'll help if that when I have time. Until there, any help is welcome. :)

Some useful links:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by gerardo-junior** [comment]
I created a pull request #15 hope it fits your guidelines

**Comment by gerardo-junior** [comment]
Do you prefer the ci service?

**Comment by GouveaHeitor** [comment]
@victorperin and @gerardo-junior 
I created some things to help the guys in the contribution, have a look at .github / please. That's enough?

**Comment by GouveaHeitor** [comment]
I will consider it OK, in case anyone deems it necessary, we can reopen.
