### ISSUE TITLE
NIPE ERROR

### ISSUE THREAD

**Issue by ROLAF1** [GouveaHeitor/nipe#19]
root@root:~/nipe#     perl nipe.pl install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version (1.6.1-2).
The following additional packages will be installed:
  tor-geoipdb torsocks
Suggested packages:
  mixmaster torbrowser-launcher tor-arm apparmor-utils obfsproxy obfs4proxy
The following NEW packages will be installed:
  tor tor-geoipdb torsocks
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2647 kB/2720 kB of archives.
After this operation, 10.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://http.kali.org/kali kali-rolling/main amd64 tor amd64 0.3.0.10-1
  404  Not Found
Err:2 http://http.kali.org/kali kali-rolling/main amd64 tor-geoipdb all 0.3.0.10-1
  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/t/tor/tor_0.3.0.10-1_amd64.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/t/tor/tor-geoipdb_0.3.0.10-1_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
--2018-04-29 16:57:31--  https://gouveaheitor.github.io/nipe/debian/torrc
Resolving gouveaheitor.github.io (gouveaheitor.github.io)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to gouveaheitor.github.io (gouveaheitor.github.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://heitorgouvea.me/nipe/debian/torrc [following]
--2018-04-29 16:57:32--  http://heitorgouvea.me/nipe/debian/torrc
Resolving heitorgouvea.me (heitorgouvea.me)... 2400:cb00:2048:1::6818:6f7b, 2400:cb00:2048:1::6818:6e7b, 104.24.111.123, ...
Connecting to heitorgouvea.me (heitorgouvea.me)|2400:cb00:2048:1::6818:6f7b|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 454 [application/octet-stream]
Saving to: ‘torrc’

torrc               100%[===================>]     454  --.-KB/s    in 0s      

2018-04-29 16:57:33 (17.9 MB/s) - ‘torrc’ saved [454/454]

Failed to stop tor.service: Unit tor.service not loaded.

Can help me?

**Comment by GouveaHeitor** [comment]
You have errors in the Kali Linux repository ... This has nothing to do with Nipe
