### ISSUE TITLE
[question] Why perl?

### ISSUE THREAD

**Issue by gerardo-junior** [GouveaHeitor/nipe#21]
I was waiting for #7 to create package for my distro, and now that issue has been concluded I came up with a question, a very honest question.

Why perl? would not .sh scripts be better? in code there is the massive use of the system function. would not it be better to run without having to install perl in minimal distros like alpine?

a sincere doubt.

**Comment by GouveaHeitor** [comment]
When I developed the Nipe, I was only 15 years old and only programmed in Perl and Pascal, so I thought I'd better choose Perl.

**Comment by GouveaHeitor** [comment]
And Perl served very well, numerous linux distributions already have the interpreter by default. Bash would really be a good choice for this current version of Nipe, but I still aim to do a lot more for him, which would make Bash bad for it. Besides being boring mt program in Bash.

**Comment by gerardo-junior** [comment]
I love perl though, but if you have been willing to talk about this. text me on the telegram. @MrGerardoJunior

**Comment by GouveaHeitor** [comment]
Ok
