### ISSUE TITLE
The script is not working properly

### ISSUE THREAD

**Issue by xzj8b3** [GouveaHeitor/nipe#22]
perl nipe.pl start
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /home/xzj8b3/perl5/lib/perl5/5.26.2/x86_64-linux-thread-multi /home/xzj8b3/perl5/lib/perl5/5.26.2 /home/xzj8b3/perl5/lib/perl5/x86_64-linux-thread-multi /home/xzj8b3/perl5/lib/perl5 /home/xzj8b3/perl5/lib/perl5/5.26.2/x86_64-linux-thread-multi /home/xzj8b3/perl5/lib/perl5/5.26.2 /home/xzj8b3/perl5/lib/perl5/x86_64-linux-thread-multi /home/xzj8b3/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at nipe.pl line 15.

Fedora 28 x64

**Comment by GouveaHeitor** [comment]
You have not run dependency installation commands ...

``` bash
cpan install Switch JSON LWP::UserAgent
```

After that, also run:

``` bash
perl nipe.pl install
```

**Comment by xzj8b3** [comment]
Obviously tried all but on Fedora 28 missing some bookstores knows me

**Comment by xzj8b3** [comment]
Obviously tried all but on Fedora 28 missing some bookstores knows me

**Comment by GouveaHeitor** [comment]
Try:

```bash
$ sudo dnf install 'perl(Switch JSON LWP::UserAgent)'
```

**Comment by rajat-np** [comment]
For beginners like me who have trouble installing the dependencies via perl nipe.pl  install , configure cpan with sudo instead of local::lib.

**Comment by GouveaHeitor** [comment]
@xzj8b3 It worked?

**Comment by GouveaHeitor** [comment]
@xzj8b3 any update??

**Comment by GouveaHeitor** [comment]
Hi Guys,

I think I got this error fixed, can someone please confirm it?

Thx.

**Comment by alshawwa** [comment]
since fedora 28 is EOL i wont bother testing the fix on it  . i will test it on fedora 29 and fedora 30 and give you a feedback shortly.

> Hi Guys,
> 
> I think I got this error fixed, can someone please confirm it?
> 
> Thx.

**Comment by alshawwa** [comment]
Alright on Both Fedora 29 and 30 
Per " Download and Install"  Section    
 cpan install Switch JSON LWP::UserAgent Config::Simple

Switch Library fails to complete installation using cpan. which in result will make perl nipe install errors out.

to fix this issue i would change/add to the documentation  to install the Perl libraries required to run Nipe using the linux distro package management instead of using cpan.
let me know if i need to test something else.

**Comment by GouveaHeitor** [comment]
Hi @alshawwa,

Thanks so much for testing Nipe and for the feedback!
Based on your answer I will mark this issue as resolved!
I just made a commit that already fixes the other problem you mentioned, I updated README with new installation instructions, could you check if that is enough?

Thx!

**Comment by xzj8b3** [comment]
Look, I no longer had time to try it, when I come back from vacation in
September I'll see it !!

Il ven 2 ago 2019, 05:27 Heitor Gouvêa <notifications@github.com> ha
scritto:

**Comment by GouveaHeitor** [comment]
Ok @xzj8b3, I will keep this issue closed until then, any new information I can reopen.
Thx!

**Comment by xzj8b3** [comment]
> Ok @xzj8b3, I will keep this issue closed until then, any new information I can reopen.
> Thx!

Forgive the delay....no I haven't tried yet because I didn't understand how script functions...It's active only with Tor enabled, otherwise is the connection normal, does it enable when you need it and just?

If Fedora 31 is more stable as soon as this happens, I don't want Tor always active!!!!
