### ISSUE TITLE
Nipe not working with nmap inside Virtualbox

### ISSUE THREAD

**Issue by falcon758** [GouveaHeitor/nipe#23]
### Expected Behavior

It was expected that nmap returned positive values which is not happening

### Actual Behavior

It must be some iptables rules that is blocking the inbound or outbound communications

### Steps to Reproduce (including precondition)

Virtualbox in Bridge adapter
Nipple start
nmap -Pn {ip}  -p {port} (-Pn since rules are blocking icmp)

### Your Environment

- OS: Ubuntu
- nipe version: last

**Comment by GouveaHeitor** [comment]
Have you had any errors with the specific nipe? Does the "status" command show your IP on the Tor network?

**Comment by GouveaHeitor** [comment]
I will simulate this scenario to try to find a solution!

**Comment by falcon758** [comment]
No error showned. Everything went normal. Just the nmap without the -Pn gives icmp error from nmap.
Nipe status is enabled and working as expected. Ip external check also confirms it's working.

Thanks

**Comment by falcon758** [comment]
The answer can be found in here https://superuser.com/questions/341946/can-i-ping-send-icmp-through-tor.
Nmap is using ip protocol ping, turning it off with -PO, solves the problem.

Thanks.

**Comment by GouveaHeitor** [comment]
Thanks @falcon758!

**Comment by GouveaHeitor** [comment]
Very nice!

**Comment by ouledzmitli** [comment]
hello can you please show us the full commend to scan with Nmap using nipe ?
