### ISSUE TITLE
go full systemd

### ISSUE THREAD

**Issue by sean9999** [GouveaHeitor/nipe#27]
the app assumes systemd, which is fine. In that case the "start" and "stop" commands should invoke systemd service commands, and a systemd service unit file should be included.

A related issue is the install script clobbers any existing tor installation without warning the user. Systemd could [help with that too](https://bugzilla.redhat.com/show_bug.cgi?id=1210837#c0)

**Comment by GouveaHeitor** [comment]
@verneck Can you help me with this?

**Comment by GouveaHeitor** [comment]
Hi @sean9999,

Have I done some implementations in this regard lately, can you take a look at the code and give me feedback on this point?

Thx

**Comment by sean9999** [comment]
sure, will do! I have been meaning to pick up some of these bugs, but I haven't had time. Great software! Really useful
