### ISSUE TITLE
install script clobbers existing tor installation

### ISSUE THREAD

**Issue by sean9999** [GouveaHeitor/nipe#28]
Install script should save it's config seperately from the main /etc/torrc, or at least warn the user before overwriting

**Comment by GouveaHeitor** [comment]
@verneck An help in this is also welcome

**Comment by verneck** [comment]
@GouveaHeitor Ok, starting job.

**Comment by GouveaHeitor** [comment]
Yay!

**Comment by naltun** [comment]
@verneck Any update on this?

**Comment by bmeneguele** [comment]
@GouveaHeitor I have some patches ready for solving this issue. Should I base it on your master branch or 'develop' one (which I just noticed you had that)?

**Comment by bmeneguele** [comment]
The PR was created based on the "develop" branch, where it seemed the files "lib/Nipe/Functions.md" is being "removed" on behalf of "lib/Nipe/Install.md" and "lib/Nipe/Helper.md".

**Comment by GouveaHeitor** [comment]
I will close this issue when the content of develop is merged to master

**Comment by GouveaHeitor** [comment]
Hi guys,

I implemented some new lines in Nipe that solve this problem! =)

You can see what has changed here: #104 

Thx
