### ISSUE TITLE
Connection Fails when I start nipe

### ISSUE THREAD

**Issue by ErikKlaw** [GouveaHeitor/nipe#31]
Hey Guys, I reached out to Heitor, and he suggested I post the thread here.  Basically I installed nipe on kali, and when I start it, the working connection fails.  I can see tor is running, and if I use the tor browser, it works fine before I start nipe.  If I stop nipe, the connection works, but only the tor browser is using the tor IP address.

Here is the thread:
Thanks for the response, here are some details:

Linux version: Kali-Rolling
Machine: Lenova Desktop

When I run 'perl nipe.pl install', no errors:
iptables is already the newest version (1.6.2-1).
tor is already the newest version (0.3.3.9-1).

I'm running ufw to manage the firewall setting, but have all ports for tor open.
53                         ALLOW       Anywhere
9053                       ALLOW       Anywhere
9050                       ALLOW       Anywhere
9040                       ALLOW       Anywhere
9051                       ALLOW       Anywhere

Any help is much appreciated.

Erik

On 2018-08-07 18:31:44 -0500 Heitor Gouvea <hi@heitorgouvea.me> wrote:

> Hello,
> 
> Very strange this mistake!
> 
> Did you notice any problems / errors during installation?
> 
> Can you give me more information about your environment ?! As a version of
> the operating system, whether it's a virtualized environment or not ... All
> kinds of information can help!
> 
> If you can open an issue in the Github repository it's even better because
> other people can help us!
> 
> Thankful!
> 
> 2018-08-06 15:02 GMT-03:00 Erik Klaw <erik-klaw@att.net>:
> 
>> I have TOR installed, and verified that the TOR Browser is working.
>> 
>> I'm trying to all of my direct my traffic through TOR using nipe, but when
>> I start nipe, I loose all connections to everything.
>> 
>> It comes back after I stop nipe.
>> 
>> I'm sure it is a port thing.  In the torrc file I have the following
>> configuration:
>> VirtualAddrNetwork 10.192.0.0/10
>> AutomapHostsOnResolve 1
>> TransPort 9040
>> SocksPort 9050
>> ControlPort 9051
>> DNSPort 53
>> RunAsDaemon 1
>> 
>> I'm also interested in adding exceptions to port 22 so I can use this
>> machine remotely while enabling nipe if it's possible.
>> 
>> Can you help out?
>> 
>> Thanks
>> 
>> Erik

**Comment by GouveaHeitor** [comment]
I made some updates, I think now it's working!
Can you download again and test one more time please?

**Comment by GouveaHeitor** [comment]
@ErikKlaw?

**Comment by GouveaHeitor** [comment]
I tested the latest version of Kali Linux and it's working perfectly, I'm closing this issue. Thank you!
