### ISSUE TITLE
install script uses numeric comparison instead of string equality, always defaults to debian

### ISSUE THREAD

**Issue by orderofwigs** [GouveaHeitor/nipe#33]
install script uses numeric comparison to check string equality, which converts the arguments to numbers first before comparing them.
$operationalSystem == "
should be 
$operationalSystem eq "
otherwise the first if statement will always be true.

**Comment by GouveaHeitor** [comment]
Dude, that really happens! Many thanks for reporting this!

It was an absurd lack of attention on my part! I'll pack it right now!

Thank you!

**Comment by orderofwigs** [comment]
no problem;)
thanks for your script!

**Comment by GouveaHeitor** [comment]
I just added the commit a9d7c52 take a look if it's OK please? If so, I'll consider it fixed ...

**Comment by orderofwigs** [comment]
looks good!

**Comment by GouveaHeitor** [comment]
Thank you again!
