### ISSUE TITLE
Renew circuits API

### ISSUE THREAD

**Issue by ggondim** [GouveaHeitor/nipe#34]

**Comment by GouveaHeitor** [comment]
You can give me an explanation of what this would be?

**Comment by ggondim** [comment]
Some way to renew TOR circuit with command shell.

Something like this:
https://stackoverflow.com/questions/9887505/how-to-change-tor-identity-in-python#19809147

**Comment by GouveaHeitor** [comment]
The "nipe.pl restart" command does this

**Comment by ggondim** [comment]
Nice!
