### ISSUE TITLE
Request: live status

### ISSUE THREAD

**Issue by lillstrumpa** [GouveaHeitor/nipe#37]
Hi, love the script.

Some functions I think it would be nice to have
It would be nice to have a status bar / icon in the menu or in the terminal where you can see/ change:

 - nipe script status ( online green ) ( red offline)
- how long it its before the tor changes the node ( countdown timer )
- maybe a timer function where you can set / change the time before the node change
- what country the the node is located
- the function to change the node

**Comment by GouveaHeitor** [comment]
Hi, I'm glad to hear that you like the project ;)

To change the node you can use the command: "perl nipe.pl restart"

As for the function to have a timer where you can set / change the time before the change: I will be developing this as soon as possible  =D

Placing the Country in the location looks like it will "pop" the information ...
