### ISSUE TITLE
Problems with iptables

### ISSUE THREAD

**Issue by Z33DD** [GouveaHeitor/nipe#45]
My nipe is installed correctly. But when I try run it, the terminal shows the following message:
`$ perl nipe.pl start`
`iptables v1.6.0: owner: Bad value for "--uid-owner" option: "tor"
Try iptables -h or iptables --help for more information.`
`iptables v1.6.0: owner: Bad value for "--uid-owner" option: "tor"
Try iptables -h or iptables --help for more information.`

I saw that there is already a closed issue dealing with this exact error message. But I don't understand the solution. The guy of original issue was using Debian, I'm using Elementary OS (based on Ubuntu 16.04.5 LTS) more info below:

`$ cat /etc/*-release`
`DISTRIB_ID="elementary"`
`DISTRIB_RELEASE=0.4.1`
`DISTRIB_CODENAME=loki`
`DISTRIB_DESCRIPTION="elementary OS 0.4.1 Loki"`
`NAME="elementary OS"`
`VERSION="0.4.1 Loki"`
`ID="elementary"`
`ID_LIKE=ubuntu`
`PRETTY_NAME="elementary OS 0.4.1 Loki"`
`VERSION_ID="0.4.1"`
`HOME_URL="http://elementary.io/"`
`SUPPORT_URL="http://elementary.io/support/"`
`BUG_REPORT_URL="https://github.com/elementary/"`
`VERSION_CODENAME=loki`
`UBUNTU_CODENAME=loki`

  And perl and iptables are already in the last version.

**Comment by alshawwa** [comment]
to make it work with elementaryOS  " a workaround"  you need to change/switch the ubuntu username for tor in Device.pm

edit Device.pm   in ../nipe/lib/Nipe/ 
and change the username under  /[U,u]ubuntu/    from "tor" to "debian-tor"  
then run the install process again  perl nipe.pl install
then start it using perl nipe start and it should establish a connection.

**Comment by Z33DD** [comment]
> to make it work with elementaryOS " a workaround" you need to change/switch the ubuntu username for tor in Device.pm
> 
> edit Device.pm in ../nipe/lib/Nipe/
> and change the username under /[U,u]ubuntu/ from "tor" to "debian-tor"
> then run the install process again perl nipe.pl install
> then start it using perl nipe start and it should establish a connection.

Ok, but what are the possiblity that this will cause problems in anothers programs?

**Comment by alshawwa** [comment]
> > to make it work with elementaryOS " a workaround" you need to change/switch the ubuntu username for tor in Device.pm
> > edit Device.pm in ../nipe/lib/Nipe/
> > and change the username under /[U,u]ubuntu/ from "tor" to "debian-tor"
> > then run the install process again perl nipe.pl install
> > then start it using perl nipe start and it should establish a connection.
> 
> Ok, but what are the possiblity that this will cause problems in anothers programs?

what kind of issues ?

**Comment by GouveaHeitor** [comment]
@Z33DD I believe it will not cause any problems...

**Comment by GouveaHeitor** [comment]
I am working at this time to correct this problem. I'll be back soon with news.

**Comment by GouveaHeitor** [comment]
Hi @Z33DD and @alshawwa,

I updated some things in the Nipe code. Can you test to confirm that everything is okay?

Thx

**Comment by Z33DD** [comment]
Hi Heitor!
I was using a old version of Elementary OS, all works ok with the new version.

**Comment by GouveaHeitor** [comment]
Thanks for the feedback!
