### ISSUE TITLE
Not Working in Kali Linux VM

### ISSUE THREAD

**Issue by caspertheghost1337** [GouveaHeitor/nipe#46]
I have reinstalled it twice following the guide and running all the necessary commands, but after I start it and check the status, it says "ERROR: sorry, it was not possible to establish a connection to the server." I am trying to run this on a VirtualBox VM on Kali Linux.

**Comment by GouveaHeitor** [comment]
Hi @caspertheghost1337,

I've made some changes to the Nipe code recently, can you see if this error has been fixed?

Thx

**Comment by GouveaHeitor** [comment]
I performed the installation of the latest version of Kali Linux on a VM, and updated its repositories.

And then I followed Nipe's step-by-step documentation, and everything went perfectly:

![Screen Shot 2019-06-25 at 20 24 05](https://user-images.githubusercontent.com/10741284/60140340-d9163080-9787-11e9-8d8a-630bd2111b17.png)
