### ISSUE TITLE
'tor' has no installation candidate error after running ./nipe.pl install command

### ISSUE THREAD

**Issue by zeeeuu** [GouveaHeitor/nipe#48]
I am trying to install it virtual machine kali linux. but the installation process stops with message 'tor has no installation candidate'

**Comment by zeeeuu** [comment]
I am trying to install it virtual machine kali linux. but the installation process stops with message 'tor has no installation candidate'

**Comment by GouveaHeitor** [comment]
If the error is still occurring, I recommend that you update the packages from your distribution before attempting to install Nipe, like this:

    $ apt-get update
    $ apt-get --list-upgrabable

And then you can run the command:

     $ perl nipe.pl install

Grateful for the attention.

**Comment by GouveaHeitor** [comment]
Please inform me if this worked ;)

**Comment by GouveaHeitor** [comment]
@zeeeuu  any update??

**Comment by GouveaHeitor** [comment]
@zeeeuu Any updates? I need to know if I can close this issue?!

**Comment by shubhamrathour98** [comment]
i am also facing same issue while i'm trying to install tor .same error message display on the screen
please help

**Comment by GouveaHeitor** [comment]
I ended up checking myself and I can conclude that Nipe is working perfectly on Kali Linux and Debian distributions.

I just updated the list of repositories and run the afore mentioned command, and then i maked the installation of Nipe.

![Screen Shot 2019-06-25 at 20 24 05](https://user-images.githubusercontent.com/10741284/60140478-6063a400-9788-11e9-8f1c-94e00848cb58.png)
