### ISSUE TITLE
[!] ERROR: sorry, it was not possible to establish a connection to the server.

### ISSUE THREAD

**Issue by S0rci3r** [GouveaHeitor/nipe#49]
Hi, 
sudo cpan install Switch JSON LWP::UserAgent ==> ok
sudo perl nipe.pl install ==> ok
sudo perl nipe.pl start ==> ok
sudo perl nipe.pl status ==> [!] ERROR: sorry, it was not possible to establish a connection to the server.

System : Manjaro Linux 18.0.2
Kernel : 4.18.20-1-MANJARO
iptables v1.8.2 (legacy)
perl v5.28.1

Thx

**Comment by naltun** [comment]
I'm getting the same error.

Sytem: Antergos
Kernel: 4.20.10-arch1-1-ARCH
iptables: 1.8.2 (legacy)
Perl: 5.28.1

Awesome project @GouveaHeitor . Would love to see this issue fixed.

**Comment by GouveaHeitor** [comment]
Hi @S0rci3r and @naltun,

I've made some changes to the Nipe code recently, can you see if this error has been fixed?

Thx

**Comment by hackerstech** [comment]
The error is not fixed

**Comment by venkateshan-s** [comment]
Still not fixed

**Comment by SurjitSahoo** [comment]
still not fixed

**Comment by anomydarklord** [comment]
> still not fixed

Friends I Recently Find the Solution of This 
Do it My way
apt reinstall tor
remove the nipe directory where you save nipe ( rm -r nipe)
then
git clone https://github.com/GouveaHeitor/nipe.git
then
{optional} apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
if needed reinstall iptables too
then
cpan install Switch JSON LWP::UserAgent
thats its
use it by perl perl nipe.pl start 
check status perl nipe.pl status
Hola you done it
Note: use of Stacer and bleachbit cause this Errror
so use by own knowledge which memory can be deleted
#anomydarklord

**Comment by anomydarklord** [comment]
> Still not fixed

Friends I Recently Find the Solution of This 
Do it My way
apt reinstall tor
remove the nipe directory where you save nipe ( rm -r nipe)
then
git clone https://github.com/GouveaHeitor/nipe.git
then
{optional} apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
if needed reinstall iptables too
then
cpan install Switch JSON LWP::UserAgent
thats its
use it by perl perl nipe.pl start 
check status perl nipe.pl status
Hola you done it
Note: use of Stacer and bleachbit cause this Errror
so use by own knowledge which memory can be deleted
#anomydarklord

**Comment by anomydarklord** [comment]
> The error is not fixed

Friends I Recently Find the Solution of This 
Do it My way
apt reinstall tor
remove the nipe directory where you save nipe ( rm -r nipe)
then
git clone https://github.com/GouveaHeitor/nipe.git
then
{optional} apt reinstall libjson-perl libswitch-perl libtest-lwp-useragent-perl
if needed reinstall iptables too
then
cpan install Switch JSON LWP::UserAgent
thats its
use it by perl perl nipe.pl start 
check status perl nipe.pl status
Hola you done it
Note: use of Stacer and bleachbit cause this Errror
so use by own knowledge which memory can be deleted
#anomydarklord

**Comment by theonelucas** [comment]
Same, not working here

**Comment by GouveaHeitor** [comment]
Hi Guys,

I think I got this error fixed, can someone please confirm it?

Thx.

**Comment by bluefangs** [comment]
Hi - Just tried this from within a docker container. Running into the exact same issue which has been reported.

```
# git clone https://github.com/GouveaHeitor/nipe
# cd nipe
# cpan install Switch JSON LWP::UserAgent Config::Simple
# perl nipe.pl install
# perl nipe.pl start
# perl nipe.pl status

[!] ERROR: sorry, it was not possible to establish a connection to the server.

```

**Comment by GouveaHeitor** [comment]
Hi @bluefangs,

Unfortunately, it is not possible to use or Nipe em um container Docker. But já estou trabalhando nisso, quiser acompanhar follow issue #16. 

I wonder if it is possible to use in the distributions mentioned above.

Thx

**Comment by bluefangs** [comment]
Thanks for your quick response. I tried it again on native Ubuntu 18.04 with some changes suggested by @anomydarklord and it seems to work. Below are the steps to get it to work:

```
apt-get apt install libjson-perl libswitch-perl libtest-lwp-useragent-perl
cpan install Switch JSON LWP::UserAgent Config::Simple
perl nipe.pl install
perl nipe.pl start
perl nipe.pl status

[+] Status: activated.	
[+] Ip: XXXXXXXX	

```

**Comment by GouveaHeitor** [comment]
Based on your response I will assume that this issue is resolved.

**Comment by enforcer-pro** [comment]
Well i'm using pop i faced same problem. Go ahead and try this command.
apt-get install --reinstall tor

perl nipe.pl start
perl nipe.pl status

**Comment by r0m305** [comment]
hey
Hoe do i fully uninstall nipe files from kali
its messed up alot
i need to reinstall it all over again

**Comment by naltun** [comment]
@r0m305 Did you ever get this taken care of?

**Comment by r0m305** [comment]
naah not yet
I'll update it first, then I'll let you know asap

**Comment by P1xart** [comment]
> Well i'm using pop-os even i faced the same problem. Go ahead and execute this command. apt-get install libjson-perl libswitch-perl libtest-lwp-useragent-perl
> 
> apt-get install --reinstall tor
> 
> perl nipe.pl start perl nipe.pl status
> 
> curl https://check.torproject.org/api/ip

it work! Th

**Comment by vermp00** [comment]
I had that error too.
But I forgot the first command. After I did "$ perl nipe.pl install" everything worked. I had nothing to reinstall.
