### ISSUE TITLE
No address associated with hostname.

### ISSUE THREAD

**Issue by TunisianWhiteHatSecurity** [GouveaHeitor/nipe#5]
The same issue  on ubuntu 14.04 and Kali Linux.

`system ("sudo wget http://heitorgouvea.me/nipe/ubuntu/torrc");`

> Resolving heitorgouvea.me (heitorgouvea.me)... failed: No address associated with hostname.
wget: unable to resolve host address ‘heitorgouvea.me’

**Comment by GouveaHeitor** [comment]
Hi, 
thank you for reporting this bug :)
and I'm sorry, my server goes down and I did not realize.
I'll try to find a solution now.

**Comment by TunisianWhiteHatSecurity** [comment]
you can put it like a raw file here, and juste change the system cmd.
`wget https://raw.githubusercontent.com/GouveaHeitor/nipe/master/LICENSE.md` for example .

**Comment by GouveaHeitor** [comment]
Ready, my server is online.
Thank you again.
:)

**Comment by TunisianWhiteHatSecurity** [comment]
Quick fix (y).
