### ISSUE TITLE
can't connect to onion

### ISSUE THREAD

**Issue by fifty59nine** [GouveaHeitor/nipe#52]
Can't load onion site's

**Comment by fifty59nine** [comment]
Guys how to open onion site's?

**Comment by GouveaHeitor** [comment]
Hey @fifty59nine,

To connect to .onion domains using Nipe, you need to perform this proxy setting on your browser:

![Screen Shot 2019-04-27 at 09 09 44](https://user-images.githubusercontent.com/10741284/56849550-4151ae80-68cc-11e9-8e3d-29bcac540089.png)


Thanks!!

**Comment by GouveaHeitor** [comment]
You can tell me if this worked?

Thx!

**Comment by GouveaHeitor** [comment]
Due to the lack of answers, I will assume that the question was answered correctly. 
Thx!
