### ISSUE TITLE
Package tor is not available, but is referred to by another package.

### ISSUE THREAD

**Issue by zakiulla** [GouveaHeitor/nipe#53]
HOW TO RESOLVE IT??

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tor is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tor' has no installation candidate

**Comment by GouveaHeitor** [comment]
Hi @zakiulla,

What distribution are you using? I recommend that you update your repositories, in the case of Debian run the command:

```bash
     $ apt update
```

Thx

**Comment by GouveaHeitor** [comment]
Hi @zakiulla,

You can you confirm if after updating the repositories, the nipe has returned to normal functioning?

Thx!!!

**Comment by GouveaHeitor** [comment]
Other important information: what distribution are you using?

**Comment by GouveaHeitor** [comment]
I ended up checking myself and I can conclude that Nipe is working perfectly on Kali Linux and Debian distributions.

I just updated the list of repositories and run the afore mentioned command, and then i maked the installation of Nipe.

![Screen Shot 2019-06-25 at 20 24 05](https://user-images.githubusercontent.com/10741284/60140301-a4a27480-9787-11e9-8a09-d56812054bdd.png)
