### ISSUE TITLE
can't start script after installed / iptables error

### ISSUE THREAD

**Issue by RosaErick** [GouveaHeitor/nipe#54]
hi, nice script but everytime i try to start it i get the following message: 

Bad value for "--uid-owner" option: "tor"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.1: owner: Bad value for "--uid-owner" option: "tor"
Try `iptables -h' or 'iptables --help' for more information.
I saw that other people are reporting the same problem but in another OS, i'm in mint 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tessa
UBUNTU_CODENAME=bionic

**Comment by Ianfinn1994** [comment]
This is the error that I had received

**Comment by solidbird** [comment]
@Ianfinn1994 
@RosaErick 
@GouveaHeitor 


Same error on my Mint 18.2 but I fixed it:

Look in your "/etc/shadow" file there should be a user called "debian-tor" or something like that
not sure how it's called on your computer but I simply went to "nipe/lib/Nipe/Start.pm" and changed the
line 13

`my $username = Nipe::Device -> getUsername();`

to

`my $username = "debian-tor";`

and this fixed it for me after "perl nipe.pl restart".

**Comment by Ianfinn1994** [comment]
Thank you man

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by solidbird** [comment]
Yeah the "getUsername()" methode doesn't really recognize Debian and Ubuntu for some reason.

**Comment by Ianfinn1994** [comment]
Or kali

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by solidbird** [comment]
Which is based on Debian

**Comment by GouveaHeitor** [comment]
Hi Guys,

I made a new merge/commit now, can you please try again?

I took a test on Kali Linux 2019!

Thx.

**Comment by solidbird** [comment]
I switched to Debian 10 and it works just fine now. Not shure for Mint or Kali.

**Comment by guimaraesjoao** [comment]
working in ubuntu 19.04

**Comment by GouveaHeitor** [comment]
Hi Guys,

Since we confirmed the operation on Debian 10, Ubuntu 19 and Kali Linux 2019: I will close this issue as resolved.

Thanks, everybody!
