### ISSUE TITLE
choose a bridge

### ISSUE THREAD

**Issue by pcoloc** [GouveaHeitor/nipe#56]
Hi,

Would it be possible to add bridges for the connection to the network for networks that have blocked tor network?

**Comment by GouveaHeitor** [comment]
Hello @pcoloc,

Your issue is very interesting!
In the past, another issue has been opened that ends up covering the same context. In case it's the issue #35 

Thank you very much for the contruibuição!

**Comment by GouveaHeitor** [comment]
Duplicated #35
