### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ghostboy-287** [GouveaHeitor/nipe#6]
hello, 
i tried your tools but i had an error 
when i try to start it by :  perl nipe.pl start 
it tell me: Error: sorry, it was not possible to establish a connection to the server.

thank you to resolve the error or giving me the solution,
Good luck :)

**Comment by GouveaHeitor** [comment]
Hi,
You can tell me what distribution you are using?
And her version, version of perl and iptables?
Thanks for feedback!!

**Comment by Ghostboy-287** [comment]
info :  
OS: gnome ubuntu  16.04.1  /32bits
iptables v1.6.0
perl v5.22.1

**Comment by GouveaHeitor** [comment]
You did "sudo perl nipe.pl install" command?

**Comment by Ghostboy-287** [comment]
yeah i did it,

**Comment by GouveaHeitor** [comment]
During installation there was no error?

**Comment by Ghostboy-287** [comment]
no errors during installation

**Comment by cyclo-techtwister** [comment]
same issue here as well running newest Kali

**Comment by GouveaHeitor** [comment]
I'll try to solve and then give an answer!
Thanks!

**Comment by mrpr1mus** [comment]
no solution yet?

**Comment by GouveaHeitor** [comment]
This was resolved in the commit: #459ed93

**Comment by Torrio888** [comment]
I have this same error

**Comment by GouveaHeitor** [comment]
@Torrio888 This error was fixed in Ubuntu, yours is happening in Linux Mint

**Comment by 1badboy** [comment]
I saw a little error with arch linux because you don't have code line 
system ("sudo wget https://gouveaheitor.github.io/nipe/arch/torrc") in the file Functions.pm

**Comment by GouveaHeitor** [comment]
Arch does not use this file

**Comment by 1badboy** [comment]
Ah ! Ok but I can't launch this programme only with arch.

**Comment by GouveaHeitor** [comment]
This error was resolved in commit  b9513db
