### ISSUE TITLE
Perl Version

### ISSUE THREAD

**Issue by UnknownSourceCode** [GouveaHeitor/nipe#60]
Bro Plz Whats The Version Of Perl Compatible With Nipe?
Else 
Whats Is Your Perl Version

**Comment by UnknownSourceCode** [comment]
Bro Plz Whats The Version Of Perl Compatible With Nipe?
Else
Whats Is Your Perl Version

**Comment by GouveaHeitor** [comment]
Hi

Nipe requires that the Perl interpreter be at least version 5.10.

Thank you.

**Comment by UnknownSourceCode** [comment]
But I Have Lastest versio of perl but Nipe D'ont Work With me

Le lun. 22 juil. 2019 4:15 PM, GouveaHeitor <notifications@github.com> a
écrit :

**Comment by GouveaHeitor** [comment]
What error is being displayed?
