### ISSUE TITLE
"Can't call method "param" on an undefined value"

### ISSUE THREAD

**Issue by Crowfunder** [GouveaHeitor/nipe#63]
Trying to run `perl nipe.pl install`, getting error:
```
Can't call method "param" on an undefined value at lib/Nipe/Device.pm line 8.
Compilation failed in require at lib/Nipe/Start.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Start.pm line 5.
Compilation failed in require at nipe.pl line 18.
BEGIN failed--compilation aborted at nipe.pl line 18.
```
Same one appears for other commands.

**Comment by GouveaHeitor** [comment]
Hi brow,
What distribution are you using?
Thx

**Comment by Crowfunder** [comment]
Hey there,
Actually that's windows cmd with cygwin installed ._.

**Comment by GouveaHeitor** [comment]
I don't particularly know Cygwin. Nipe uses the file "/etc/os-release", does this file exist in your environment? From this file, Nipe defines the system user and many other things.

**Comment by Crowfunder** [comment]
Sorry for long response, i had some trouble with perl, i tried to do it directly through cygwin shell, but perl's broken there. Also running setup.sh returned the same error. Answering to your question, no there isn't any file like one you said.

**Comment by GouveaHeitor** [comment]
Unfortunately Nipe only operates on Linux based distributions, so the current version will not work on Cygwin. Based on this I will close this issue.

If you want, you can open a new issue suggesting a new implementation of nipe for Cygwin.

Thanks for listening.

**Comment by MirAtharHussain** [comment]
Can't call method "param" on an undefined value
