### ISSUE TITLE
nipe info

### ISSUE THREAD

**Issue by xzj8b3** [GouveaHeitor/nipe#66]
I would like to know if "nipe" proxa in a fixed way or you can activate it, disable it each time please

**Comment by GouveaHeitor** [comment]
Nipe is dynamic, you decide when it is operating.

You can check if it is active using command:

$ perl nipe.pl status

To start just use the command:

$ perl nipe.pl start

And then it will work until you turn it off:

$ perl nipe.pl stop

**Comment by xzj8b3** [comment]
> Nipe is dynamic, you decide when it is operating.
> 
> You can check if it is active using command:
> 
> $ perl nipe.pl status
> 
> To start just use the command:
> 
> $ perl nipe.pl start
> 
> And then it will work until you turn it off:
> 
> $ perl nipe.pl stop

will go to fedora 31 or better wait for final release?? I would not like to miss any bookshops!!!

**Comment by xzj8b3** [comment]
> Nipe is dynamic, you decide when it is operating.
> 
> You can check if it is active using command:
> 
> $ perl nipe.pl status
> 
> To start just use the command:
> 
> $ perl nipe.pl start
> 
> And then it will work until you turn it off:
> 
> $ perl nipe.pl stop

For installation in case???? I haven't gotten 29 reply to the text anymore!!!!!
