### ISSUE TITLE
nipe info 

### ISSUE THREAD

**Issue by xzj8b3** [GouveaHeitor/nipe#67]
Will it already work for fedora 31 or risk running into missing bookstores?

Can you show me how to install it?

**Comment by GouveaHeitor** [comment]
Hi @xzj8b3,

I noticed that you have a lot of questions about Nipe, could you send me an email or a message on Telegram to talk about all of them?

My e-mail is: hi@heitorgouvea.me and my Telegram is: @GouveaHeitor 

Thx
