### ISSUE TITLE
Can't call method "param" on an undefined value at lib/Nipe/Device.pm line 8.

### ISSUE THREAD

**Issue by RamiDzPower** [GouveaHeitor/nipe#68]
Trying to do a manual install by running  the command ` $ perl nipe.pl install`
But getting this error 
`Can't call method "param" on an undefined value at lib/Nipe/Device.pm line 8.
Compilation failed in require at lib/Nipe/Start.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Start.pm line 5.
Compilation failed in require at nipe.pl line 18.
BEGIN failed--compilation aborted at nipe.pl line 18.`

Using MacOs 10.15.1

`***:nipe ****$ cpan install Switch JSON LWP::UserAgent 
Reading '/Users/****/.cpan/Metadata'
  Database was generated on Mon, 25 Nov 2019 01:55:44 GMT
Switch is up to date (2.17).
JSON is up to date (4.02).
LWP::UserAgent is up to date (6.42).`

**Comment by GouveaHeitor** [comment]
Hi @RamiDzPower 

Today nipe is not operational on MacOS.
It is currently functional in the following distributions: Debian, Ubuntu, Fedora, Arch Linux & Cent OS; Other distributions based on those mentioned above also support Nipe.

Thx

**Comment by brunocasanova** [comment]
Are there new updates on this? Tried to manual install it on MacOS today and still didn't work.

**Comment by GouveaHeitor** [comment]
Hi @brunocasanova,

Nipe does not support MacOS, only for Linux distributions such as Ubuntu, Debian, Arch Linux and Fedora.

Thx
