### ISSUE TITLE
You can distribute nipe.pl packed using App::FatPacker

### ISSUE THREAD

**Issue by dvinciguerra** [GouveaHeitor/nipe#69]
**Is your feature request related to a problem? Please describe.**
You can distribute your application packed way using App::FatPacker to keep all dependencies in a single file.

**Describe the solution you'd like**
```
$ cpanm App::FatPacker
$ fatpack pack nipe.pl > nipe.packed.pl
``` 

**Describe alternatives you've considered**
N/A

**Additional context**

example of a packed file:
[nipe.packed.pl.txt](https://github.com/GouveaHeitor/nipe/files/3892338/nipe.packed.pl.txt)

**Comment by GouveaHeitor** [comment]
Your recommendation is super interesting! Can you open a Pull Request with this please?

**Comment by dvinciguerra** [comment]
Sure! =)
