### ISSUE TITLE
Completely Redesign Installation

### ISSUE THREAD

**Issue by Miserlou** [GouveaHeitor/nipe#7]
This script appears to get foreign objects, via plaintext HTTP, using sudo, from your websever, and put them into the user's conf. This is a terrible idea for a number of obvious reasons.

I strongly, strongly suggest that you come up with another way of solving this problem.

**Comment by GouveaHeitor** [comment]
Hi @Miserlou,
I can understand the concern ...
Could you give me an alternative?
Thank you!

**Comment by ksyz** [comment]
Sure. For example, make use of perl [__DATA__](http://perldoc.perl.org/perldata.html#Special-Literals) section.

**Comment by gerardo-junior** [comment]
are there any contributing guidelines?

**Comment by Pedro-Souza** [comment]
Gits fix this?

**Comment by GouveaHeitor** [comment]
I'm thinking of creating a folder called "configs /", and put the files in it. What about?

**Comment by Pedro-Souza** [comment]
Very better, this eliminates 1 requests

**Comment by gerardo-junior** [comment]
@GouveaHeitor I think it's much better, read a file as a template and apply the changes specifics

**Comment by GouveaHeitor** [comment]
Fixed on commit 6f57586855b8bf8d8ca98087585fbb2eedb7db0d
