### ISSUE TITLE
Can't locate Config/Simple.pm

### ISSUE THREAD

**Issue by alexblyz** [GouveaHeitor/nipe#71]
Can't locate Config/Simple.pm in @INC (you may need to install the Config::Simple module) (@INC contains: ./lib/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at lib/Nipe/Device.pm line 5.

**Comment by GouveaHeitor** [comment]
Hi @alexblyz,

You need install the all dependencies: cpan install Switch JSON LWP::UserAgent Config::Simple

Thx

**Comment by GouveaHeitor** [comment]
Hi @alexblyz,
Did you successfully install?
Thx.

**Comment by GouveaHeitor** [comment]
I am closing this issue, please comment any news when you find it necessary.

My comment above certainly solves your problem.

**Comment by mansurabbas** [comment]
Thanks alot This  cpan install Switch JSON LWP::UserAgent Config::Simple

Help me alot

**Comment by mansurabbas** [comment]
it solve my  same error

**Comment by GouveaHeitor** [comment]
Hi @mansurabbas, 

First, the correct dependencies are:

```
 sudo cpan install Try::Tiny Config::Simple JSON
```

Also, I need to know if an error is occurring when trying to install... Without having visibility of the error, I can't help you.

Thx

**Comment by GouveaHeitor** [comment]
Hi @mansurabbas any update about this?

**Comment by GouveaHeitor** [comment]
Hi Folks, I am closing this issue, please comment any news when you find it necessary.

**Comment by allelive** [comment]
> sudo cpan install Try::Tiny Config::Simple JSON

grazie o risolto grazie

**Comment by particleofmass** [comment]
Nothing worked for me. I get the same error listed above

**Comment by htrgouvea** [comment]
The command to fix it is:

```bash
sudo cpan install Config::Simple
```
