### ISSUE TITLE
Switch.pm does not exist

### ISSUE THREAD

**Issue by GigaHorse-ex** [GouveaHeitor/nipe#73]
I checked the update folder and everything but Switch.pm existed, I am trying to configure on Ubuntu, and it requires the Switch.pm in order to run

**Comment by GouveaHeitor** [comment]
Hi,

You need install the all dependencies: cpan install Switch JSON LWP::UserAgent Config::Simple

Thx

**Comment by GouveaHeitor** [comment]
I am closing this issue, please comment any news when you find it necessary.

My comment above certainly solves your problem.
