### ISSUE TITLE
nipe can't start 

### ISSUE THREAD

**Issue by Sumit-Jungi** [GouveaHeitor/nipe#74]
perl nipe.pl start
Can't locate Config/Simple.pm in @INC (you may need to install the Config::Simple module) (@INC contains: ./lib/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at lib/Nipe/Device.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Device.pm line 5.
Compilation failed in require at lib/Nipe/Start.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Start.pm line 5.
Compilation failed in require at nipe.pl line 6.
BEGIN failed--compilation aborted at nipe.pl line 6.

**Comment by GouveaHeitor** [comment]
Hi,

You need install the all dependencies: cpan install Switch JSON LWP::UserAgent Config::Simple

Thx

**Comment by GouveaHeitor** [comment]
I am closing this issue, please comment any news when you find it necessary.

My comment above certainly solves your problem.
