### ISSUE TITLE
Install troubleshooting

### ISSUE THREAD

**Issue by smecham** [GouveaHeitor/nipe#79]
Noob here, but I'm trying to follow the install procedure and I'm getting the following error. already did the config::simple step with no errors. Any idea how to fix?
<img width="548" alt="Screen Shot 2020-01-15 at 13 58 10" src="https://user-images.githubusercontent.com/24739448/72462528-42e73d80-379f-11ea-931b-2dd663898e65.png">

**Comment by bmeneguele** [comment]
@smecham it seems your linux distro don't have the "ID_LIKE" key in its /etc/os-release file. I'm actually working in a patch to solve this issue. For the time being, and if you feel comfortable, you can change the line there mentioned directly:

1. edit lib/Nipe/Device.pm in line 8 with:
`my $id_like   = $config -> param('ID_LIKE');` 
to 
`my $id_like   = $config -> param('ID');`

There'll be two var with the same value, I know, but until it doesn't get solved I would suggest this quick solution. Of course, that's my opinion. On the other hand you can just wait for the solution getting release, which I'm working on.

**Comment by smecham** [comment]
Thanks for your quick reply! I made that change in the device.pm file but got the same error message as before, any other tips? (I'm also fine just waiting for the patch if there's not an easy way to troubleshoot on my end).  Thanks again!

**Comment by GouveaHeitor** [comment]
Hi @smecham,
What Linux distribution are you using?

The @bmeneguele solution is now available in the "develop" branch if you want to use it.

I will work to bring the solution developed by @bmeneguele as soon as possible to the official version.

Thx

**Comment by bmeneguele** [comment]
> Hi @smecham,
> What Linux distribution are you using?

Also, could you provide the content in your /etc/os-release file?

`cat /etc/os-release`

IIRC there are some distro that don't ship with it. If that's your case, try to `cat /usr/lib/os-release`.

> The @bmeneguele solution is now available in the "develop" branch if you want to use it.

@GouveaHeitor I think my last PR doesn't solve this issue directly. There's another PR I'm planning to send still today, or tomorrow, that would solve the issue itself, if the distro she's using indeed has /etc/os-release. Otherwise we need to rethink on how to get the distro information.

**Comment by smecham** [comment]
Hey yall, thanks for addressing this so fast. I was using Tails but I upgraded to version 4.2.2 yesterday and its now working, so I'm not sure what the issue was before but it appears to have resolved. I also tried it on my ubuntu bistro and its working there too!

**Comment by GouveaHeitor** [comment]
Thanks so much for the feedback @smecham!
