### ISSUE TITLE
[!] ERROR: sorry, it was not possible to establish a connection to the server.

### ISSUE THREAD

**Issue by Creaprog** [GouveaHeitor/nipe#8]
Hello,

sudo perl nipe.pl start

[!] ERROR: sorry, it was not possible to establish a connection to the server.

Why ?

**Comment by Creaprog** [comment]
Because I didn't : [code]sudo perl nipe.pl install[/code] 

Sorry.

**Comment by GouveaHeitor** [comment]
No problem... =D
