### ISSUE TITLE
Implement IPTables::libiptc

### ISSUE THREAD

**Issue by GouveaHeitor** [GouveaHeitor/nipe#82]
Implementing Lib IPTables::libiptc can stop using command execution directly in the system, and abstract it for the code.

This will make the code more readable and simpler, making maintenance and new implementations easier.

In addition to resolving some conflicts between multi-compatibility.

Reference:
https://metacpan.org/pod/IPTables::libiptc

**Comment by bmeneguele** [comment]
Hmm.. one thing I just noticed is that this lib isn't being maintained anymore :(. I'm going search for another one that could replace the system() calls.
