### ISSUE TITLE
Nipe Won't Start 

### ISSUE THREAD

**Issue by Darth4212** [GouveaHeitor/nipe#9]
Whenever I try to start nipe I get this output: `Can't locate Nipe/Stop.pm in @INC (you may need to install the Nipe::Stop module) (@INC contains: ./lib/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/darth/Desktop/Programs/nipe/nipe line 19.
BEGIN failed--compilation aborted at /home/darth/Desktop/Programs/nipe/nipe line 19.`
What do I do?

**Comment by GouveaHeitor** [comment]
I'll check the reason and try to fix it.
Thanks for making this bug...

**Comment by GouveaHeitor** [comment]
I think this bug has already been resolved @Darth4212!
Could you test Nipe again?

**Comment by GouveaHeitor** [comment]
This error was resolved in commit  b9513db
