### ISSUE TITLE
Lightweight HTTP module 

### ISSUE THREAD

**Issue by bmeneguele** [GouveaHeitor/nipe#90]
@GouveaHeitor what do you think if we replace LWP::UserAgent by [HTTP::Tiny](https://metacpan.org/pod/HTTP::Tiny) on Status.pm? HTTP::Tiny is already used by cpanm, easing Nipe's installation process and timing, since LWP::UserAgent brings a lot of other modules together.

Even more considering we only perform a single and simple request.
I can work on that if you agree.

**Comment by GouveaHeitor** [comment]
Bruno, thanks again for that!

I will open a PR in a few minutes adding this suggestion!

**Comment by GouveaHeitor** [comment]
After a look at PR #91 91 and see if that was your recommendation ...

If you want to open an additional PR, feel free.

**Comment by bmeneguele** [comment]
Just checked and that's correct!
Thanks @GouveaHeitor
