### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by willkof1** [GouveaHeitor/nipe#94]
Durante o processo de instalação recebo o seguinte erro:

perl nipe.pl install
Can't locate Config/Simple.pm in @INC (you may need to install the Config::Simple module) (@INC contains: ./lib/ /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/i386-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base) at lib/Nipe/Device.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Device.pm line 5.
Compilation failed in require at lib/Nipe/Start.pm line 5.
BEGIN failed--compilation aborted at lib/Nipe/Start.pm line 5.
Compilation failed in require at nipe.pl line 7.
BEGIN failed--compilation aborted at nipe.pl line 7.

**Comment by GouveaHeitor** [comment]
Oi @willkof1,

Você precisa instalar as dependencias que estão listadas na README.md, pode fazer isso com o seguinte comando:

$ sudo cpan install Switch JSON LWP::UserAgent Config::Simple

Se precisa de mais algum esclarecido, por favor me avise.
Abraços!

**Comment by willkof1** [comment]
Olá Heitor, eu fiz isso. Segui exatamente como documentado.

**Comment by willkof1** [comment]
Vejo alguns not found nos logs durante a instalação das dependências e este abaixo por exemplo:

cpan install Confi::Simple module
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/root/.cpan/Metadata'
  Database was generated on Thu, 13 Feb 2020 14:55:42 GMT
Warning: Cannot install Confi::Simple, don't know what it is.
Try the command

    i /Confi::Simple/

to find objects with matching identifiers.
Running install for module 'module'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/A/AD/ADAMK/Devel-Leak-Module-0.02.tar.gz
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/A/AD/ADAMK/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/A/AD/ADAMK/Devel-Leak-Module-0.02.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring A/AD/ADAMK/Devel-Leak-Module-0.02.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Test::Script 1.07 not found.

**Comment by GouveaHeitor** [comment]
Você está digitando o comando com um pequeno erro... Está faltando a letra "g" palavra Config pelo que percebi

**Comment by willkof1** [comment]
Provavelmente erro de copy/paste aqui. O comando de instalação ta certo.

**Comment by bmeneguele** [comment]
> Provavelmente erro de copy/paste aqui. O comando de instalação ta certo.

Hmmm.. mas esse 

```i /Confi::Simple/```

não foi retirado direto da saida do comando? Porque esse erro acontece quando o cpan não acha o pacote, e se você usou `Confi::Simple` ao invés de `Config::Simple` esse seria exatamente o erro.

> A instalação no Debian é este comando mesmo ?

Os nomes dos módulos instalados pelo CPAN são independentes da distro que está utilizando, por isso deveria funcionar normalmente.

**Comment by willkof1** [comment]
Bom como te falei tentei outras vezes exatamente como a documentação e não
funcionou.
Mas blz. Obrigado. Fica pra próxima.

Em ter, 18 de fev de 2020 20:36, Bruno Meneguele <notifications@github.com>
escreveu:

**Comment by willkof1** [comment]
.
